### PR TITLE
chore: add X-lab related info

### LINKED ISSUE #13: [docs] update website with x-lab related info

### PR DESCRIPTION
**Pull request by zhicheng-ning**
resolve #13

### CODE REVIEW

**Comment by tyn1998** [comment]
来点图看看嘛

**Comment by zhicheng-ning** [comment]
I need front-end engineer's help 🥲 , It would be nice to have some lab material, which I'll use later.

https://www.x-lab.info/X-lab-website/

**Comment by tyn1998** [comment]
Haha, in fact I am reminding you to put some screenshots in PR description so 路人 like me can know what changes in this PR right away~

**Comment by zhicheng-ning** [comment]
long way to go

image

**Comment by will-ww** [comment]
Cool~

**Pull request merged**
